*** Variables ***
${titleModalLogin}          id:logInModalLabel
${str_titlePageLogin}       Log in

${txt_loginusername}        id:loginusername
${txt_loginpassword}        id:loginpassword

${btn_close}                xpath://*[@id="logInModal"]/div/div/div[@class="modal-footer"]/button[1]
${btn_login}                xpath://*[@id="logInModal"]/div/div/div[@class="modal-footer"]/button[2]
${btn_close_top}            xpath://*[@id="logInModal"]/div/div/div[@class="modal-title"]/button